name: LightSelector
main: me.yourname.lightselector.LightSelector
version: 1.1
api-version: 1.20
commands:
  lightmode:
    description: Control light selection
    usage: /lightmode [save add/replace|toggle|on|off]
